"""add premium subscriptions

Revision ID: 5d339deb073c
Revises: 2c6c3c579839
Create Date: 2025-12-07 22:52:50.540100

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d339deb073c"
down_revision: Union[str, Sequence[str], None] = "2c6c3c579839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription",
        sa.Column(
            "is_premium", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "is_premium")
    # ### end Alembic commands ###
