"""add moderator users

Revision ID: ad14dc436a24
Revises: 5d339deb073c
Create Date: 2025-12-07 23:01:46.867220

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from db.models import Base

# revision identifiers, used by Alembic.
revision: str = "ad14dc436a24"
down_revision: Union[str, Sequence[str], None] = "5d339deb073c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moderators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["videos.id"],
            name=op.f("fk_moderators_user_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "user_id", name=op.f("pk_moderators")),
    )

    op.bulk_insert(
        sa.Table("moderators", Base.metadata),
        [{"id": 1, "created_at": "2025-12-07", "user_id": 1}],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("moderators")
    # ### end Alembic commands ###
