"""remove playlists

Revision ID: e3d90608cd2d
Revises: ad14dc436a24
Create Date: 2025-12-07 23:18:21.190483

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3d90608cd2d"
down_revision: Union[str, Sequence[str], None] = "ad14dc436a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_video")
    op.drop_table("playlists")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('playlists_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DATE(),
            server_default=sa.text("CURRENT_DATE"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name="fk_playlists_author_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_playlists"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "playlist_video",
        sa.Column("playlist_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("video_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
            name=op.f("fk_playlist_video_playlist_id_playlists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_playlist_video_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "playlist_id", "video_id", name=op.f("pk_playlist_video")
        ),
    )
    # ### end Alembic commands ###
